# 项目启动端口
server:
  address: :2002
  # debug模式
  model: debug
  # release模式
  #model:release

# 数据库配置
db:
  dialects: mysql
  host: 127.0.0.1
  port: 3306
  db: WeAssist
  username: root
  password: 123456
  charset: utf8mb4
  # 最大空闲数
  maxIdle: 50
  # 最大连接数
  maxOpen: 150
  # 批量获取或插入数
  batchSize: 100

# redis配置
redis:
  address: 127.0.0.1:6379
  password:

# 图片地址和ip
imageSettings:
  # 本地磁盘地址
  # uploadDir: /go-admin-api/upload/
  uploadDir: /Users/daniel/Desktop/daniel/go/src/WeAssist/upload/
  # 本地ip地址
  imageHost: http://localhost:2002

# log日志配置
log:
  path: ./log
  name: sys
  # 输出到控制台
  model: console
  # 输出到文件
  # model: file

# 定时任务执行周期
cron:
  run: 5 0 * * *